name: flutter_map_location_marker_example
description: Example of FlutterMapLocationMarkerPlugin
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.2
  flutter_map: 8.3.1
  flutter_map_location_marker:
    path: ../
  geolocator: any
  latlong2: any

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
