name: flutter_map_location_marker
description: A flutter map plugin for displaying device current location.
version: 10.3.0
repository: https://github.com/tlserver/flutter_map_location_marker
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.12.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.0
  flutter_rotation_sensor: ^0.3.0
  geolocator: ^14.0.0
  latlong2: ">=0.9.1 <0.11.0"

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
